// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"
import panier_controller from "./panier_controller"
import tags_controller from "./tags_controller"
const channels = require.context(".", true, /_channel\.js$/)
channels.keys().forEach(channels)

application.register("panier", panier_controller)
application.register("tags", tags_controller)

